(function(){
  const supa=window.supabaseClient; if(!supa)return;
  const ADMINS=['eugene.aquila06@gmail.com','eugenecard.market@gmail.com'];
  function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
  async function bearer(){const {data}=await supa.auth.getSession();return data.session?.access_token||'';}
  async function call(method,body){const token=await bearer();const r=await fetch('/api/admin/oauth-clients',{method,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:body?JSON.stringify(body):undefined});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Request failed (${r.status})`);return d;}
  function panel(){if(document.getElementById('oauth-admin-panel'))return;const s=document.createElement('section');s.id='oauth-admin-panel';s.className='glass rounded-3xl p-6 mt-5';s.innerHTML=`<div class="flex flex-col md:flex-row md:items-center justify-between gap-3"><div><div class="text-[10px] uppercase tracking-widest font-black text-violet-300">Developer Access</div><h2 class="text-xl font-black mt-1">OAuth & API Connections</h2><p class="text-xs text-slate-500 mt-1">Register trusted applications, control redirect URIs and revoke access without exposing secrets.</p></div><button id="oauth-refresh" class="px-3 py-2 rounded-xl bg-slate-800 text-xs font-bold">Refresh</button></div><div class="grid lg:grid-cols-3 gap-3 mt-4"><input id="oauth-id" class="rounded-xl bg-slate-950 border border-slate-800 p-3 text-xs" placeholder="Client ID e.g. lunarist"><input id="oauth-name" class="rounded-xl bg-slate-950 border border-slate-800 p-3 text-xs" placeholder="Application name"><input id="oauth-redirect" class="rounded-xl bg-slate-950 border border-slate-800 p-3 text-xs lg:col-span-3" placeholder="Exact redirect URI (https://...)"><button id="oauth-add" class="rounded-xl bg-violet-600 p-3 text-xs font-black">Register PKCE Client</button></div><div id="oauth-secret" class="hidden mt-3 rounded-xl bg-amber-500/10 border border-amber-500/20 p-3 text-xs text-amber-200"></div><div id="oauth-list" class="space-y-2 mt-5"><p class="text-xs text-slate-500">Loading clients…</p></div>`;document.querySelector('#pending-actions-list')?.closest('section')?.before(s);document.getElementById('oauth-refresh').onclick=load;document.getElementById('oauth-add').onclick=add;load();}
  async function load(){const list=document.getElementById('oauth-list');if(!list)return;try{const rows=await call('GET');list.innerHTML=rows.length?rows.map(c=>`<div class="rounded-2xl bg-slate-950 border border-slate-800 p-4 flex flex-col md:flex-row md:items-center justify-between gap-3"><div><div class="font-black text-sm">${esc(c.client_name)} <span class="text-[10px] text-slate-500">${esc(c.client_id)}</span></div><div class="text-[11px] text-slate-400 mt-1">${esc((c.redirect_uris||[]).join(' • '))}</div><div class="text-[10px] text-slate-500 mt-1">Scopes: ${esc((c.allowed_scopes||[]).join(', '))}</div></div><div class="flex gap-2"><button data-id="${esc(c.client_id)}" data-active="${c.is_active}" class="oauth-toggle px-3 py-2 rounded-lg ${c.is_active?'bg-emerald-500/10 text-emerald-300':'bg-rose-500/10 text-rose-300'} text-[10px] font-black">${c.is_active?'ACTIVE':'DISABLED'}</button><button data-id="${esc(c.client_id)}" class="oauth-delete px-3 py-2 rounded-lg bg-rose-500/10 text-rose-300 text-[10px] font-black">Delete</button></div></div>`).join(''):'<p class="text-xs text-slate-500">No OAuth clients registered.</p>';list.querySelectorAll('.oauth-toggle').forEach(b=>b.onclick=async()=>{await call('PATCH',{client_id:b.dataset.id,is_active:b.dataset.active!=='true'});load();});list.querySelectorAll('.oauth-delete').forEach(b=>b.onclick=async()=>{if(confirm(`Delete OAuth client ${b.dataset.id}?`)){await call('DELETE',{client_id:b.dataset.id});load();}});}catch(e){list.innerHTML=`<p class="text-xs text-rose-300">${esc(e.message)}</p>`;}}
  async function add(){const id=document.getElementById('oauth-id').value.trim(),name=document.getElementById('oauth-name').value.trim(),redirect=document.getElementById('oauth-redirect').value.trim();const out=document.getElementById('oauth-secret');if(!id||!name||!redirect){out.className='mt-3 rounded-xl bg-rose-500/10 border border-rose-500/20 p-3 text-xs text-rose-200';out.textContent='Client ID, name and exact redirect URI are required.';return;}try{const d=await call('POST',{client_id:id,client_name:name,redirect_uris:[redirect],allowed_scopes:['openid','profile','email']});out.className='mt-3 rounded-xl bg-emerald-500/10 border border-emerald-500/20 p-3 text-xs text-emerald-200';out.textContent=`Client ${d.client_id} registered. PKCE is enabled; no client secret is required.`;document.getElementById('oauth-id').value='';document.getElementById('oauth-name').value='';document.getElementById('oauth-redirect').value='';load();}catch(e){out.className='mt-3 rounded-xl bg-rose-500/10 border border-rose-500/20 p-3 text-xs text-rose-200';out.textContent=e.message;}}
  async function init(){const {data:{user}}=await supa.auth.getUser();if(user&&ADMINS.includes(String(user.email||'').toLowerCase()))panel();}
  setTimeout(init,300);supa.auth.onAuthStateChange(()=>setTimeout(init,0));
})();
