/* Eugene Card — Supabase-only auth/profile bootstrap */
(function () {
  const URL = 'https://tsjgvzpzfjyecnginipt.supabase.co';
  const KEY = 'sb_publishable_o3oWlPh_EPj5xd0GBjDWYQ_UhVicSH3';
  const ADMIN_EMAILS = ['eugene.aquila06@gmail.com', 'eugenecard.market@gmail.com'];
  if (!window.supabase) throw new Error('Supabase SDK missing');
  const sb = window.supabaseClient = window.supabase.createClient(URL, KEY, { auth:{ persistSession:true, autoRefreshToken:true, detectSessionInUrl:true, flowType:'pkce' } });
  window.isUserAdmin = email => ADMIN_EMAILS.includes(String(email||'').trim().toLowerCase());
  window.EUGENE_ADMIN_EMAIL = ADMIN_EMAILS[0];
  const toLegacyAuthUser = user => { if(!user)return null; const m=user.user_metadata||{}; return {...user,uid:user.id,displayName:m.full_name||m.name||user.email||'',photoURL:m.avatar_url||m.picture||null,emailVerified:!!user.email_confirmed_at,providerData:user.identities||[]}; };
  const originalGetSession=sb.auth.getSession.bind(sb.auth);
  sb.auth.getSession=async(...args)=>{const r=await originalGetSession(...args);if(r?.data?.session?.user)r.data.session.user=toLegacyAuthUser(r.data.session.user);return r;};
  const originalOnAuthStateChange=sb.auth.onAuthStateChange.bind(sb.auth);
  sb.auth.onAuthStateChange=callback=>originalOnAuthStateChange((event,session)=>callback(event,session?{...session,user:toLegacyAuthUser(session.user)}:null));
  const normalize=r=>r?({...r,name:r.name??r.display_name??'',display_name:r.display_name??r.name??'',avatarUrl:r.avatarUrl??r.avatar_url??'',isPlusMember:r.isPlusMember??r.is_plus_member??false,socialIg:r.socialIg??r.social_ig??'',socialTwitter:r.socialTwitter??r.social_twitter??'',socialTiktok:r.socialTiktok??r.social_tiktok??'',socialWeb:r.socialWeb??r.social_web??'',profileCompleted:r.profileCompleted??r.profile_completed??false,isAdmin:r.isAdmin??r.role==='admin'}):null;
  async function ensureSupabaseProfile(user){if(!user)return null;const email=String(user.email||'').toLowerCase().trim();let {data:p}=await sb.from('profiles').select('*').eq('id',user.id).maybeSingle();if(!p){const {data:legacy}=await sb.from('legacy_profiles').select('*').eq('email',email).maybeSingle();const m=legacy||{};const name=m.display_name||user.user_metadata?.full_name||user.user_metadata?.name||email.split('@')[0];const row={id:user.id,username:m.username||name.toLowerCase().replace(/[^a-z0-9_]+/g,'_').replace(/^_+|_+$/g,''),display_name:name,avatar_url:m.avatar_url||user.user_metadata?.avatar_url||`https://api.dicebear.com/7.x/identicon/svg?seed=${encodeURIComponent(email)}`,bio:m.bio||'',role:window.isUserAdmin(email)?'admin':'user',is_plus_member:!!m.is_plus_member,social_ig:m.social_ig||'',social_twitter:m.social_twitter||'',social_tiktok:m.social_tiktok||'',social_web:m.social_web||'',profile_completed:!!m.profile_completed,updated_at:new Date().toISOString()};const created=await sb.from('profiles').upsert(row,{onConflict:'id'}).select().single();p=created.data||row;}else if(window.isUserAdmin(email)&&p.role!=='admin'){const updated=await sb.from('profiles').update({role:'admin',updated_at:new Date().toISOString()}).eq('id',user.id).select().single();p=updated.data||{...p,role:'admin'};}return normalize(p);}
  window.ensureSupabaseProfile=ensureSupabaseProfile;
  const syncLegacyCurrentUser=user=>{const legacyUser=user?toLegacyAuthUser(user):null;if(window.auth)window.auth.currentUser=legacyUser;window.currentUser=legacyUser;if(legacyUser)ensureSupabaseProfile(legacyUser).catch(e=>console.warn('Profile bootstrap:',e));};
  const routeAfterLogin=async user=>{if(!user||window.__roleLandingRedirect)return;const path=location.pathname;const isDashboard=/\/(user-dashboard|admin-dashboard)\.html$/.test(path);if(isDashboard)return;const profile=await ensureSupabaseProfile(user);const target=profile?.role==='admin'&&window.isUserAdmin(user.email)?'./admin-dashboard.html':'./user-dashboard.html';window.__roleLandingRedirect=true;location.replace(target);};
  const syncExistingSession=async()=>{try{const {data}=await originalGetSession();const user=data?.session?.user||null;syncLegacyCurrentUser(user);if(user&&location.hash!=='#no-redirect')await routeAfterLogin(user);}catch(e){console.warn('Session bootstrap:',e);}};
  const bridgeAuthListener=()=>{if(!window.auth||window.auth.__supabaseBridgeInstalled)return!!window.auth;const original=window.auth.onAuthStateChanged;if(typeof original!=='function')return false;window.auth.onAuthStateChanged=callback=>original(user=>{const normalized=user?toLegacyAuthUser(user):null;syncLegacyCurrentUser(normalized);callback(normalized);if(normalized)routeAfterLogin(normalized);});window.auth.__supabaseBridgeInstalled=true;if(window.auth.currentUser)syncLegacyCurrentUser(window.auth.currentUser);return true;};
  let bridgeAttempts=0;const installBridge=()=>{if(bridgeAuthListener()||++bridgeAttempts>=50)return;setTimeout(installBridge,50);};installBridge();
  const enhanceProfileButton=()=>{const c=document.getElementById('auth-header-container');if(!c||!window.currentUser)return;if(c.querySelector('[data-profile-customize-label]'))return;const b=c.querySelector('button[aria-label="Edit Profile"]');if(!b)return;b.classList.remove('p-2');b.classList.add('px-2.5','py-2');b.innerHTML='<i class="fa-solid fa-user-pen text-xs mr-1.5"></i><span data-profile-customize-label>Customize</span>';b.title='Customize Profile';b.setAttribute('aria-label','Customize Profile');};
  const watchProfileHeader=()=>{enhanceProfileButton();const c=document.getElementById('auth-header-container');if(!c||c.__profileEnhancer)return;c.__profileEnhancer=true;new MutationObserver(()=>enhanceProfileButton()).observe(c,{childList:true,subtree:true});};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',watchProfileHeader);else watchProfileHeader();setTimeout(watchProfileHeader,1000);setTimeout(watchProfileHeader,2500);setTimeout(syncExistingSession,0);
  originalOnAuthStateChange((event,session)=>{const user=session?.user||null;syncLegacyCurrentUser(user);setTimeout(watchProfileHeader,50);if(event==='SIGNED_IN'&&user)routeAfterLogin(user);});
})();