(() => {
  'use strict';
  const SUPABASE_URL='https://tsjgvzpzfjyecnginipt.supabase.co';
  const SUPABASE_KEY='sb_publishable_o3oWlPh_EPj5xd0GBjDWYQ_UhVicSH3';
  const ADMINS=new Set(['eugene.aquila06@gmail.com','eugenecard.market@gmail.com']);
  const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,flowType:'pkce',storageKey:'eugene-card-supabase-auth'}});
  const state={user:null,profile:null,cards:[],favorites:new Set(),view:new URLSearchParams(location.search).get('view')||'market',query:'',filter:'all',loading:true};
  const app=document.getElementById('app');
  const money=n=>`$${Number(n||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`;
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const admin=()=>!!state.user&&(ADMINS.has((state.user.email||'').toLowerCase())||state.profile?.role==='admin');
  function toast(msg,error=false){const d=document.createElement('div');d.className='toast'+(error?' error':'');d.textContent=msg;document.getElementById('toast-root').appendChild(d);setTimeout(()=>d.remove(),3200)}
  function requireAuth(){if(!state.user){openLogin();return false}return true}
  async function ensureProfile(user){
    if(!user)return null;
    let {data,error}=await sb.from('profiles').select('*').eq('id',user.id).maybeSingle(); if(error)throw error;
    const email=(user.email||'').toLowerCase();
    if(!data){const name=user.user_metadata?.full_name||user.user_metadata?.name||email.split('@')[0]||'Collector';const row={id:user.id,username:name.toLowerCase().replace(/[^a-z0-9_]/g,'_').slice(0,40),display_name:name,avatar_url:user.user_metadata?.avatar_url||user.user_metadata?.picture||'',bio:'',role:ADMINS.has(email)?'admin':'user',is_plus_member:false,social_ig:'',social_twitter:'',social_tiktok:'',social_web:'',profile_completed:false,updated_at:new Date().toISOString()};const r=await sb.from('profiles').insert(row).select('*').single();if(r.error)throw r.error;data=r.data}
    else if(ADMINS.has(email)&&data.role!=='admin'){const r=await sb.from('profiles').update({role:'admin',updated_at:new Date().toISOString()}).eq('id',user.id).select('*').single();if(!r.error)data=r.data}
    return data;
  }
  async function load(){
    state.loading=true;render();
    const session=await sb.auth.getSession();state.user=session.data.session?.user||null;
    try{state.profile=await ensureProfile(state.user)}catch(e){console.error(e);state.profile=null}
    const {data:cards,error}=await sb.from('cards').select('*').order('created_at',{ascending:false});
    if(!error)state.cards=cards||[];
    if(state.user){const {data:f}=await sb.from('app_data').select('data').eq('collection','favorites').eq('owner_id',state.user.id);state.favorites=new Set((f||[]).map(x=>x.data?.card_id).filter(Boolean))}
    state.loading=false;render();
  }
  async function saveData(collection,data,id){
    if(!requireAuth())return;
    const row={collection,id:id||crypto.randomUUID(),owner_id:state.user.id,data,updated_at:new Date().toISOString()};const r=await sb.from('app_data').upsert(row,{onConflict:'collection,id'});if(r.error)toast(r.error.message,true);return !r.error;
  }
  function layout(){return `<div class="shell ${admin()?'is-admin':''}">
    <header class="topbar"><div class="topbar-inner"><a class="brand" href="./"><span class="brand-mark">E</span>Eugene Card</a>
      <nav class="nav"><button data-view="market">Marketplace</button><button data-view="inventory">Inventory</button><button data-view="sell">Sell</button><button data-view="trade">Trade</button><button data-view="favorites">Favorites</button><button data-view="profile">Profile</button><button class="admin-only" data-view="admin">Admin Hub</button><button class="admin-only" data-view="analytics">Analytics</button><button class="admin-only" data-view="revenue">Revenue</button></nav>
      <div class="auth-area">${state.user?`<button class="user-btn" id="user-toggle"><img src="${esc(state.profile?.avatar_url||'https://api.dicebear.com/7.x/initials/svg?seed='+encodeURIComponent(state.profile?.display_name||state.user.email))}" style="width:28px;height:28px;border-radius:50%;vertical-align:middle;margin-right:6px">${esc(state.profile?.display_name||state.user.email)}</button><div class="user-menu" id="user-menu"><div class="user-head"><strong>${esc(state.profile?.display_name||'Collector')}</strong><span>${esc(state.user.email||'')}</span></div><button data-view="profile">Profile & customization</button>${admin()?'<button data-view="admin">Admin Hub</button><button data-view="inventory">Inventory</button>':''}<button id="logout">Log out</button></div>`:`<button class="btn primary" id="login">Log in</button>`}</div></div></header>
    <main class="main">${state.loading?'<div class="panel">Loading Eugene Card…</div>':views()}</main>
    <nav class="mobile-nav"><button data-view="market">⌂<br>Market</button><button data-view="inventory">▣<br>Inventory</button><button data-view="sell">＋<br>Sell</button><button data-view="favorites">♡<br>Saved</button><button data-view="profile">●<br>Profile</button></nav>
    <div class="modal-root" id="modal"></div></div>`}
  function views(){switch(state.view){case'inventory':return inventory();case'sell':return sell();case'trade':return trade();case'favorites':return favorites();case'profile':return profile();case'admin':return adminView();case'analytics':return analytics();case'revenue':return revenue();default:return market()}}
  function market(){const cards=filtered();return `<section class="hero"><div class="panel"><div class="eyebrow">Premium collectible marketplace</div><h1>Collect rare.<br><span class="gold-text">Own yours.</span></h1><p>Discover numbered Eugene Cards, compare floor prices, save favorites and build your collection. Your inventory and profile follow you across devices through Supabase.</p><div class="hero-actions"><button class="btn primary" data-view="market">Explore cards</button><button class="btn" data-view="sell">List a card</button></div><div class="stats"><div class="stat"><b>${state.cards.length}</b><span>Total cards</span></div><div class="stat"><b>${state.cards.filter(c=>c.status!=='sold').length}</b><span>Available</span></div><div class="stat"><b>${state.cards.filter(c=>String(c.type).toLowerCase().includes('premium')).length}</b><span>Premium</span></div></div></div><div class="panel"><div class="eyebrow">Your collection</div>${state.user?`<h2>${esc(state.profile?.display_name||'Collector')}</h2><p class="muted">${state.favorites.size} saved cards · ${ownedCards().length} owned</p><button class="btn" data-view="profile">Customize profile</button>`:`<h2>Start collecting</h2><p class="muted">Log in once and keep your profile, favorites and inventory synchronized on every device.</p><button class="btn primary" id="hero-login">Log in with Google</button>`}</div></section><div class="section-title"><h2>Marketplace</h2><span>${cards.length} shown</span></div><div class="toolbar"><input class="input search" id="search" value="${esc(state.query)}" placeholder="Search name, serial, edition…"><select class="select" id="filter" style="max-width:180px"><option value="all">All cards</option><option value="standard" ${state.filter==='standard'?'selected':''}>Standard</option><option value="premium" ${state.filter==='premium'?'selected':''}>Premium</option><option value="available" ${state.filter==='available'?'selected':''}>Available</option></select></div>${cards.length?`<div class="grid">${cards.map(card).join('')}</div>`:'<div class="empty">No cards match your search.</div>'}`}
  function filtered(){let q=state.query.toLowerCase();return state.cards.filter(c=>{let text=[c.name,c.serial,c.edition,c.tier,c.printing].join(' ').toLowerCase();let okq=!q||text.includes(q);let okf=state.filter==='all'||(state.filter==='available'&&c.status!=='sold')||String(c.type).toLowerCase()===state.filter;return okq&&okf})}
  function card(c){const premium=String(c.type).toLowerCase().includes('premium');return `<article class="card ${premium?'premium':''}"><div class="card-media">${c.img_url?`<img loading="lazy" src="${esc(c.img_url)}" alt="${esc(c.name)}">`:'<div class="fallback">◇</div>'}<span class="badge ${premium?'gold':'blue'}">${esc(c.type)}</span><button class="fav ${state.favorites.has(c.id)?'on':''}" data-fav="${esc(c.id)}">${state.favorites.has(c.id)?'♥':'♡'}</button></div><div class="card-body"><div class="card-title">${esc(c.name)}</div><div class="meta">${esc(c.serial||c.sn||'Unnumbered')} · ${esc(c.edition||'Eugene Card')}</div><div class="price-row"><div class="price">${money(c.price)} <small>USD</small></div><div class="meta">${esc(c.status||'available')}</div></div><div class="card-actions"><button class="btn primary" data-buy="${esc(c.id)}" ${c.status==='sold'?'disabled':''}>${c.status==='sold'?'Sold':'Buy'}</button><button class="btn" data-trade-card="${esc(c.id)}">Trade</button></div></div></article>`}
  function ownedCards(){if(!state.user)return[];const email=(state.user.email||'').toLowerCase();return state.cards.filter(c=>String(c.owner||'').toLowerCase()===email||c.owner===state.user.id)}
  function inventory(){if(!requireAuthView())return loginPrompt('Inventory');const mine=ownedCards();return `<div class="section-title"><h2>Your Inventory</h2><span>${mine.length} cards</span></div>${mine.length?`<div class="grid">${mine.map(card).join('')}</div>`:'<div class="empty">No cards are assigned to your account yet. Cards you buy can appear here after the ownership record is updated.</div>'}`}
  function requireAuthView(){return!!state.user}
  function loginPrompt(title){return `<div class="panel" style="max-width:700px;margin:auto;text-align:center"><div class="eyebrow">${title}</div><h2>Log in to continue</h2><p class="muted">Your session is persistent across refreshes and browser navigation.</p><button class="btn primary" id="login">Log in with Google</button></div>`}
  function sell(){if(!state.user)return loginPrompt('Sell');return `<div class="panel"><div class="eyebrow">Marketplace</div><h2>List a card</h2><p class="muted">Create a listing request. Your profile and listing are stored in Supabase.</p><form id="sell-form" class="form-grid"><div class="field"><label>Card name</label><input class="input" name="name" required placeholder="Eugene Card #001"></div><div class="field"><label>Price (USD)</label><input class="input" name="price" type="number" min="0" step="0.01" required></div><div class="field"><label>Serial / number</label><input class="input" name="serial"></div><div class="field"><label>Edition</label><input class="input" name="edition" placeholder="Standard / Premium"></div><div class="field full"><label>Image URL</label><input class="input" name="image_url" type="url"></div><div class="field full"><label>Description</label><textarea class="textarea" name="description" rows="4"></textarea></div><div class="field full"><button class="btn primary">Submit listing</button></div></form></div>`}
  function trade(){if(!state.user)return loginPrompt('Trade');return `<div class="panel"><div class="eyebrow">Collector exchange</div><h2>Start a trade</h2><form id="trade-form" class="form-grid"><div class="field"><label>Card you want</label><input class="input" name="want" required placeholder="Card ID or name"></div><div class="field"><label>Your card / offer</label><input class="input" name="offer" required placeholder="Card ID or description"></div><div class="field full"><label>Message</label><textarea class="textarea" name="message" rows="4"></textarea></div><div class="field full"><button class="btn primary">Send trade offer</button></div></form></div>`}
  function favorites(){if(!state.user)return loginPrompt('Favorites');const mine=state.cards.filter(c=>state.favorites.has(c.id));return `<div class="section-title"><h2>Favorites</h2><span>${mine.length} saved</span></div>${mine.length?`<div class="grid">${mine.map(card).join('')}</div>`:'<div class="empty">Tap ♡ on any card to save it here.</div>'}`}
  function profile(){if(!state.user)return loginPrompt('Profile');return `<div class="panel"><div class="profile"><div><img class="avatar" src="${esc(state.profile?.avatar_url||'https://api.dicebear.com/7.x/initials/svg?seed='+encodeURIComponent(state.profile?.display_name||state.user.email))}"><div style="margin-top:10px;text-align:center"><button class="btn" id="customize">Customize profile</button></div></div><div><div class="eyebrow">Collector profile ${admin()?'· ADMIN':''}</div><h2>${esc(state.profile?.display_name||'Collector')}</h2><p class="muted">@${esc(state.profile?.username||'collector')}</p><p>${esc(state.profile?.bio||'No bio yet.')}</p><div class="stats"><div class="stat"><b>${ownedCards().length}</b><span>Owned</span></div><div class="stat"><b>${state.favorites.size}</b><span>Favorites</span></div><div class="stat"><b>${state.profile?.is_plus_member?'PLUS':'FREE'}</b><span>Membership</span></div></div></div></div></div>`}
  function adminView(){if(!admin())return loginPrompt('Admin');const available=state.cards.filter(c=>c.status!=='sold').length,sold=state.cards.length-available;return `<div class="section-title"><h2>Admin Command Center</h2><span>Protected by Supabase role + admin email</span></div><div class="admin-grid"><div class="metric"><span>Total cards</span><b>${state.cards.length}</b></div><div class="metric"><span>Available</span><b>${available}</b></div><div class="metric"><span>Sold</span><b>${sold}</b></div><div class="metric"><span>Inventory value</span><b>${money(state.cards.reduce((a,c)=>a+Number(c.price||0),0))}</b></div><div class="metric"><span>Premium</span><b>${state.cards.filter(c=>String(c.type).toLowerCase().includes('premium')).length}</b></div><div class="metric"><span>Admin</span><b>Active</b></div></div><div class="section-title"><h2>Inventory management</h2></div><div class="table-wrap"><table class="table"><thead><tr><th>Card</th><th>Serial</th><th>Type</th><th>Price</th><th>Status</th><th>Owner</th></tr></thead><tbody>${state.cards.map(c=>`<tr><td>${esc(c.name)}</td><td>${esc(c.serial||c.sn||'—')}</td><td>${esc(c.type)}</td><td>${money(c.price)}</td><td>${esc(c.status)}</td><td>${esc(c.owner||'Marketplace')}</td></tr>`).join('')}</tbody></table></div>`}
  function analytics(){if(!admin())return loginPrompt('Analytics');const avg=state.cards.length?state.cards.reduce((a,c)=>a+Number(c.price||0),0)/state.cards.length:0;return `<div class="section-title"><h2>Analytics</h2></div><div class="admin-grid"><div class="metric"><span>Average card price</span><b>${money(avg)}</b></div><div class="metric"><span>Standard</span><b>${state.cards.filter(c=>String(c.type).toLowerCase()==='standard').length}</b></div><div class="metric"><span>Premium</span><b>${state.cards.filter(c=>String(c.type).toLowerCase()==='premium').length}</b></div></div><div class="panel" style="margin-top:16px"><h3>Market snapshot</h3><p class="muted">Analytics are calculated from the live Supabase card inventory. Add transaction records to app_data to expand this view with historical volume and price charts.</p></div>`}
  function revenue(){if(!admin())return loginPrompt('Revenue');const sold=state.cards.filter(c=>c.status==='sold');const total=sold.reduce((a,c)=>a+Number(c.price||0),0);return `<div class="section-title"><h2>Revenue</h2></div><div class="admin-grid"><div class="metric"><span>Recorded sold cards</span><b>${sold.length}</b></div><div class="metric"><span>Recorded revenue</span><b>${money(total)}</b></div><div class="metric"><span>Average sold price</span><b>${money(sold.length?total/sold.length:0)}</b></div></div><div class="notice">Revenue is based on cards currently marked <b>sold</b> in Supabase.</div>`}
  function openLogin(){const m=document.getElementById('modal');m.className='modal-root open';m.innerHTML=`<div class="modal"><div class="eyebrow">Eugene Card</div><h2>Welcome back</h2><p class="muted">Use your Google account. Supabase keeps the session persistent across refresh and browser navigation.</p><button class="btn primary" id="google-login" style="width:100%">Continue with Google</button><div class="modal-actions"><button class="btn ghost" id="close-modal">Cancel</button></div></div>`;document.getElementById('close-modal').onclick=()=>m.className='modal-root';document.getElementById('google-login').onclick=async()=>{const {error}=await sb.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.origin+location.pathname}});if(error)toast(error.message,true)}}
  function customize(){if(!requireAuth())return;const p=state.profile||{};const m=document.getElementById('modal');m.className='modal-root open';m.innerHTML=`<div class="modal"><h2>Customize Profile</h2><form id="profile-form"><div class="field"><label>Display name</label><input class="input" name="display_name" value="${esc(p.display_name||'')}"></div><div class="field"><label>Username</label><input class="input" name="username" value="${esc(p.username||'')}"></div><div class="field"><label>Avatar URL</label><input class="input" name="avatar_url" value="${esc(p.avatar_url||'')}"></div><div class="field"><label>Bio</label><textarea class="textarea" name="bio" rows="4">${esc(p.bio||'')}</textarea></div><div class="modal-actions"><button type="button" class="btn" id="close-modal">Cancel</button><button class="btn primary">Save profile</button></div></form></div>`;document.getElementById('close-modal').onclick=()=>m.className='modal-root';document.getElementById('profile-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);const r=await sb.from('profiles').update({display_name:f.get('display_name'),username:f.get('username'),avatar_url:f.get('avatar_url'),bio:f.get('bio'),profile_completed:true,updated_at:new Date().toISOString()}).eq('id',state.user.id).select('*').single();if(r.error)toast(r.error.message,true);else{state.profile=r.data;m.className='modal-root';toast('Profile saved');render()}}}
  async function toggleFav(id){if(!requireAuth())return;const exists=state.favorites.has(id);if(exists){const r=await sb.from('app_data').delete().eq('collection','favorites').eq('id',id).eq('owner_id',state.user.id);if(r.error)toast(r.error.message,true);else state.favorites.delete(id)}else{const r=await sb.from('app_data').upsert({collection:'favorites',id,owner_id:state.user.id,data:{card_id:id},updated_at:new Date().toISOString()},{onConflict:'collection,id'});if(r.error)toast(r.error.message,true);else state.favorites.add(id)}render()}
  async function buy(id){if(!requireAuth())return;const c=state.cards.find(x=>x.id===id);if(!c)return;const ok=confirm(`Request purchase of ${c.name} for ${money(c.price)}?`);if(!ok)return;const good=await saveData('orders',{card_id:id,price:c.price,status:'pending',card_name:c.name},crypto.randomUUID());if(good)toast('Purchase request recorded. An admin can complete the ownership transfer.')}
  async function submitSell(e){e.preventDefault();const f=new FormData(e.target);const ok=await saveData('listings',{name:f.get('name'),price:Number(f.get('price')),serial:f.get('serial'),edition:f.get('edition'),image_url:f.get('image_url'),description:f.get('description'),status:'pending'});if(ok){e.target.reset();toast('Listing submitted')}}
  async function submitTrade(e){e.preventDefault();const f=new FormData(e.target);const ok=await saveData('trades',{want:f.get('want'),offer:f.get('offer'),message:f.get('message'),status:'pending'});if(ok){e.target.reset();toast('Trade offer sent')}}
  function bind(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;history.pushState({view:state.view},'',`?view=${encodeURIComponent(state.view)}`);render()});const login=document.getElementById('login')||document.getElementById('hero-login');if(login)login.onclick=openLogin;const u=document.getElementById('user-toggle');if(u)u.onclick=()=>document.getElementById('user-menu').classList.toggle('open');const logout=document.getElementById('logout');if(logout)logout.onclick=async()=>{await sb.auth.signOut();state.user=null;state.profile=null;state.favorites.clear();state.view='market';history.replaceState({},'',location.pathname);render();toast('Logged out')};const cus=document.getElementById('customize');if(cus)cus.onclick=customize;const search=document.getElementById('search');if(search){search.oninput=e=>{state.query=e.target.value;document.querySelector('.grid')?.replaceWith(Object.assign(document.createElement('div'),{className:'grid',innerHTML:filtered().map(card).join('')}));bindCardEvents()}}const filter=document.getElementById('filter');if(filter)filter.onchange=e=>{state.filter=e.target.value;render()};const sf=document.getElementById('sell-form');if(sf)sf.onsubmit=submitSell;const tf=document.getElementById('trade-form');if(tf)tf.onsubmit=submitTrade;bindCardEvents()}
  function bindCardEvents(){document.querySelectorAll('[data-fav]').forEach(b=>b.onclick=()=>toggleFav(b.dataset.fav));document.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>buy(b.dataset.buy));document.querySelectorAll('[data-trade-card]').forEach(b=>b.onclick=()=>{state.view='trade';render();const i=document.querySelector('[name=want]');if(i)i.value=b.dataset.tradeCard})}
  function render(){app.innerHTML=layout();document.querySelectorAll('.nav [data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));bind()}
  window.addEventListener('popstate',()=>{state.view=new URLSearchParams(location.search).get('view')||'market';render()});window.addEventListener('pageshow',()=>sb.auth.getSession().then(({data})=>{const u=data.session?.user||null;if((u?.id||null)!==(state.user?.id||null))load()}));
  sb.auth.onAuthStateChange(async(event,session)=>{if(event==='SIGNED_OUT'){state.user=null;state.profile=null;state.favorites.clear();render();return}if(session?.user){state.user=session.user;try{state.profile=await ensureProfile(state.user)}catch(e){console.error(e)}if(!state.cards.length){const r=await sb.from('cards').select('*').order('created_at',{ascending:false});if(!r.error)state.cards=r.data||[]}render()}});
  load();
})();
