const crypto=require('crypto');
const {json,hash,supabaseUser,db,randomToken,safeEqual}=require('../oauth/_lib');
const ADMINS=new Set(['eugene.aquila06@gmail.com','eugenecard.market@gmail.com']);
async function admin(req){const token=String(req.headers.authorization||'').replace(/^Bearer\s+/i,'').trim();const u=await supabaseUser(token);return u?.email&&ADMINS.has(String(u.email).toLowerCase())?u:null;}
module.exports=async function handler(req,res){
 try{if(!await admin(req))return json(res,403,{error:'forbidden'});
  if(req.method==='GET'){const rows=await db('oauth_clients?select=client_id,client_name,redirect_uris,allowed_scopes,is_active,created_at,updated_at&order=created_at.desc');return json(res,200,rows||[]);}
  if(req.method==='POST'){const b=req.body||{};const clientId=String(b.client_id||'').trim();const name=String(b.client_name||'').trim();const redirects=Array.isArray(b.redirect_uris)?b.redirect_uris.map(String).map(s=>s.trim()).filter(Boolean):[];const allowed=Array.isArray(b.allowed_scopes)?b.allowed_scopes.map(String).filter(Boolean):['openid','profile'];if(!/^[a-z0-9._-]{2,64}$/i.test(clientId)||!name||!redirects.length)return json(res,400,{error:'invalid_client_configuration'});const secret=b.client_secret?String(b.client_secret):null;const payload={client_id:clientId,client_name:name,client_secret_hash:secret?hash(secret):null,redirect_uris:redirects,allowed_scopes:allowed,is_active:true};await db('oauth_clients',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(payload)});return json(res,201,{client_id:clientId,client_name:name,client_secret:secret,redirect_uris:redirects,allowed_scopes:allowed});}
  if(req.method==='PATCH'){const b=req.body||{};const id=String(b.client_id||'');if(!id)return json(res,400,{error:'missing_client_id'});const patch={};if(typeof b.is_active==='boolean')patch.is_active=b.is_active;if(Array.isArray(b.redirect_uris))patch.redirect_uris=b.redirect_uris.map(String).map(s=>s.trim()).filter(Boolean);if(Array.isArray(b.allowed_scopes))patch.allowed_scopes=b.allowed_scopes.map(String).filter(Boolean);if(b.client_name)patch.client_name=String(b.client_name).trim();patch.updated_at=new Date().toISOString();await db(`oauth_clients?client_id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify(patch)});return json(res,200,{ok:true});}
  if(req.method==='DELETE'){const id=String(req.body?.client_id||req.query?.client_id||'');if(!id)return json(res,400,{error:'missing_client_id'});await db(`oauth_clients?client_id=eq.${encodeURIComponent(id)}`,{method:'DELETE'});return json(res,200,{ok:true});}
  return json(res,405,{error:'method_not_allowed'});
 }catch(e){console.error(e);return json(res,500,{error:'oauth_client_admin_failed'});}
};
